banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_cnab1: 14..14
cod_movimentacao: 15..16
agencia: 19..23
dv_agencia: 24..24
conta_corrente: 25..36
dv_conta: 37..37
dv_conta_agencia: 38..38
id_titulo: 39..58
codigo_rateio: 59..59
tipo_valor: 60..60
valor_rateio: 61..75
beneficiario_banco: 76..78
beneficiario_agencia: 79..83
beneficiario_dv_agencia: 84..84
beneficiario_conta_corrente: 85..96
beneficiario_dv_conta: 97..97
beneficiario_dv_conta_agencia: 98..98
beneficiario_nome: 99..138
beneficiario_parcela: 139..144
beneficiario_floating: 145..147
beneficiario_data_credito: 148..155
motivo_ocorrido: 156..165