banco: 0..2
lote: 3..6
registro: 7..7
tipo_operacao: 8..8
tipo_servico: 9..10
res_cnab1: 11..12
layout_lote: 13..15
res_cnab2: 16..16
tipo_empresa: 17..17
num_empresa: 18..31
cod_beneficiario: 32..32
cod_beneficiario_cedente: 33..38
cod_caixa: 39..53
mantenedora_agencia: 54..58
mantenedora_dv: 59..59
benefeciario_cod: 60..60
convenio_cod: 61..66
modelo_personalizado_cod: 67..73
cod_caixa: 74..74
nome_empresa: 75..104
federacao_cod: 105..105
mensagem_1: 106..144
confederacao_cod: 145..145
mensagem_2: 146..184
mensagem_3: 146..184
numero_retorno: 185..196
data_gracavacao: 197..204
data_credito: 205..212
dados_febraban: 213..239