banco: 0..2
lote: 3..6
tipo_registro: 7..7
num_registro: 8..12
segmento: 13..13
res_cnab1: 14..14
cod_movimentacao: 15..16
capital_social_empresa: 17..29
capital_socital_estabelecimento: 30..42
numero_empregados: 43..51
total_remuneracao: 52..64
total_empregado: 65..73
cod_cnae: 74..78
tipo_entidade: 79..79
cod_entidade: 80..84
tipo_arrecadacao: 85..85
valor_pago: 86..100
valor_liquido: 101..115
valor_credito: 116..130
outras_despesas: 131..145
data_ocorrencia: 146..153
data_credito: 154..161
res_cnab_2: 162..165
data_debito_tarifa: 166..173
cod_pagador: 174..188
res_cnab3: 189..218
res_cnab_3: 219..239